replicaCount: 1
image:
  repository: vaultwarden/server
  tag: "1.30.5"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: vaultwarden.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
database:
  name: vaultwarden
  user: vaultwarden
  password: vaultwardenpassword
  host: vaultwarden-db-rw
  port: 5432
