apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-config
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
{{ .Values.config | toYaml | indent 2 }}
